// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aljlqaevxxjwxmhxgczm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsamxxYWV2eHhqd3htaHhnY3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzY1ODcsImV4cCI6MjA2OTAxMjU4N30.oies2fFWakhFz9Iyn_4Rqed8Wl-W4SEMfD0HhRNNptc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});